### ISSUE TITLE
Any way to setup the I2P Firefox profile separate from Jpackaged I2P similar to the older I2P Firefox profiles.

### ISSUE THREAD

**Issue by Destroyinator69420** [i2p/i2p.firefox#1]
I prefer the classic I2P install with a separate JVM, i2p router and browser profile. I don't think that the Jpackage should go away since it is good for other people, but there should be an option to get the I2P browser profile separate from the I2P router. It simply does not make sense for me to have multiple JVMs on my computer since I use several other apps written in Java, Freenet and Minecraft among them.

**Comment by eyedeekay** [comment]
I followed up with you on Reddit I think? I did a lot to improve compatibility with the "classic" install procedure. All features will be fully restored in 1.8.0 in 3 days.

**Comment by eyedeekay** [comment]
As far as I can tell the compat issues with the IzPack(Separate JVM) installer have all been fixed, closing this, feel free to re-open if you find more.
