### ISSUE TITLE
Not able to install :(

### ISSUE THREAD

**Issue by lakshits11** [i2p/i2p.firefox#2]
When I try to install, I get two things sequentially:

1.
![image](https://github.com/i2p/i2p.firefox/assets/54276661/4a952c08-a651-43b7-b7f5-6ab96ba9c1f4)

2. 
![image](https://github.com/i2p/i2p.firefox/assets/54276661/437ff796-4e23-4e09-9cce-70598ab19b98)

**Comment by eyedeekay** [comment]
You're not using this installer, you're using the old-school decoupled installer. Install Java and the thing you have will work.
